In [10]:
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('csv_normalized_tokenized-Copy1.csv')

In [4]:
import csv
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

infile = 'csv_normalized_tokenized-Copy1.csv'
data = "Comms"
labels = "Classe"


class Classifier():
    def __init__(self):
        self.train_set, self.test_set = self.load_data()
        self.counts, self.test_counts = self.vectorize()
        self.classifier = self.train_model()

    def load_data(self):

        df = pd.read_csv(infile, header=0, error_bad_lines=False)
        train_set, test_set = train_test_split(df, test_size=.3)
        return train_set, test_set

    def train_model(self):
        classifier = BernoulliNB()
        targets = self.train_set[labels]
        classifier.fit(self.counts, targets)
        return classifier


    def vectorize(self):

        vectorizer = TfidfVectorizer(min_df=5,
                                 max_df = 0.8,
                                 sublinear_tf=True,
                                 ngram_range = (1,2),
                                 use_idf=True)
        counts = vectorizer.fit_transform(self.train_set[data])
        test_counts = vectorizer.transform(self.test_set[data])

        return counts, test_counts

    def evaluate(self):
        test_counts,test_set = self.test_counts, self.test_set
        predictions = self.classifier.predict(test_counts)
        print (classification_report(test_set[labels], predictions))
        print ("The accuracy score is {:.2%}".format(accuracy_score(test_set[labels], predictions)))


    def classify(self, input):
        input_text = input

        input_vectorizer = TfidfVectorizer(min_df=5,
                                 max_df = 0.8,
                                 sublinear_tf=True,
                                 ngram_range = (1,2),
                                 use_idf=True)
        input_counts = input_vectorizer.transform(input_text)
        predictions = self.classifier.predict(input_counts)
        print(predictions)

myModel = Classifier()

text = ['I like this I feel good about it', 'give me 5 dollars']

myModel.classify(text)
myModel.evaluate()

C:\Users\lucas\AppData\Local\Temp/ipykernel_6004/4032695868.py:17: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  self.train_set, self.test_set = self.load_data()


ValueError: np.nan is an invalid document, expected byte or unicode string.

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.svm import LinearSVC
import pickle


# Train the classification model
def train_model():
    df = pd.read_csv('csv_normalized_tokenized-Copy1.csv')

    X_train, X_test, y_train, y_test = train_test_split(df['Comms'], df['Classe'], random_state=0)

    count_vect = CountVectorizer()
    X_train_counts = count_vect.fit_transform(X_train)
    tfidf_transformer = TfidfTransformer()
    X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

    model = LinearSVC().fit(X_train_tfidf, y_train)

    # Save the vectorizer
    vec_file = 'vectorizer.pickle'
    pickle.dump(count_vect, open(vec_file, 'wb'))

    # Save the model
    mod_file = 'classification.model'
    pickle.dump(model, open(mod_file, 'wb'))


# Load the classification model from disk and use for predictions
def classify_utterance(utt):
    # load the vectorizer
    loaded_vectorizer = pickle.load(open('vectorizer.pickle', 'rb'))

    # load the model
    loaded_model = pickle.load(open('classification.model', 'rb'))

    # make a prediction
    print(loaded_model.predict(loaded_vectorizer.transform([utt])))
    

In [42]:
df.shape

(4589, 14)

In [49]:
data = pd.read_csv("csv_without_null_comments2.csv")
data.shape

(4829, 10)

In [58]:
data = data[data['Comment'].notna()]
data.shape

(4588, 12)

In [51]:
data.rename(columns={'Classe;;;;;;;;;;;;;;;;;':'Classe'}, inplace=True)
data['Classe'] = data["Classe"].str.replace(";","")
data.head()

ID                                  UUID  Trip ID  \
0  19469  5f090183-575f-4b68-bfd8-8ca64e271f60      NaN   
1  19487  79fa4190-76bd-4b48-a6aa-c22b1f5f9355      NaN   
2  31714  7ff43434-065d-4a08-83b2-9a6077c9d0a3  49934.0   
3  31956  737320b2-0e91-42fa-9f48-3e651b453e02  50342.0   
4  32873  1d83eae9-2658-4cee-9afe-6f4824d3ec47  51909.0   

                                             Comment  Rate  \
0                        Sans assistance électrique    1.0   
1                              Pas de frein arrière    3.0   
2                                          Ct génial   0.0   
3                                        Marche pas    0.0   
4  Vélo très bien mais « vélo rue » du Borrigo av...   3.0   

                    Created At                   Updated At  \
0     2021-09-26T11:30:17.535Z     2021-09-26T11:30:17.535Z   
1     2021-09-26T14:01:24.832Z     2021-09-26T14:01:24.832Z   
2  2022-02-21T16:43:55.149001Z  2022-02-21T16:43:55.149001Z   
3  2022-02-25T12:28:03.504405Z  2022-02-25T12:28:03.504405Z   
4  2022-03-09T09:26:07.593932Z  2022-03-09T09:26:07.593932Z   

                User Old ID               Trip Old ID         Classe  
0  60d193e09485da0e5c6c5c51  6150591710168f3d48342d26      Technique  
1  608156dcdeb7eb746a8b7ba0  61507aff10168f3d483c51c9      Technique  
2                       NaN                       NaN  Pas technique  
3                       NaN         ;;;;;;;;;;;;;;;;;            NaN  
4                       NaN                       NaN  Pas technique

In [57]:
Com2 = data["Comment"].tolist()
print('Le nombre de commentaires est :',len(Com2))

Le nombre de commentaires est : 4588


In [53]:
Com2 = data["Comment"].tolist()
print('Le nombre de commentaires est :',len(Com2))

Le nombre de commentaires est : 4828


In [54]:
data['Comms'] = Com2
data.head()

ID                                  UUID  Trip ID  \
0  19469  5f090183-575f-4b68-bfd8-8ca64e271f60      NaN   
1  19487  79fa4190-76bd-4b48-a6aa-c22b1f5f9355      NaN   
2  31714  7ff43434-065d-4a08-83b2-9a6077c9d0a3  49934.0   
3  31956  737320b2-0e91-42fa-9f48-3e651b453e02  50342.0   
4  32873  1d83eae9-2658-4cee-9afe-6f4824d3ec47  51909.0   

                                             Comment  Rate  \
0                        Sans assistance électrique    1.0   
1                              Pas de frein arrière    3.0   
2                                          Ct génial   0.0   
3                                        Marche pas    0.0   
4  Vélo très bien mais « vélo rue » du Borrigo av...   3.0   

                    Created At                   Updated At  \
0     2021-09-26T11:30:17.535Z     2021-09-26T11:30:17.535Z   
1     2021-09-26T14:01:24.832Z     2021-09-26T14:01:24.832Z   
2  2022-02-21T16:43:55.149001Z  2022-02-21T16:43:55.149001Z   
3  2022-02-25T12:28:03.504405Z  2022-02-25T12:28:03.504405Z   
4  2022-03-09T09:26:07.593932Z  2022-03-09T09:26:07.593932Z   

                User Old ID               Trip Old ID         Classe  \
0  60d193e09485da0e5c6c5c51  6150591710168f3d48342d26      Technique   
1  608156dcdeb7eb746a8b7ba0  61507aff10168f3d483c51c9      Technique   
2                       NaN                       NaN  Pas technique   
3                       NaN         ;;;;;;;;;;;;;;;;;            NaN   
4                       NaN                       NaN  Pas technique   

                                               Comms  
0                        Sans assistance électrique   
1                              Pas de frein arrière   
2                                          Ct génial  
3                                        Marche pas   
4  Vélo très bien mais « vélo rue » du Borrigo av...

In [55]:
data['Length'] = data['Comment'].apply(lambda x: len(str(x)))
#aaaa.drop(aaaa[aaaa['Length'] <= 2].index, inplace=True)
print("Mean rate :",data["Rate"].mean())
print("Mean comments length :",data["Length"].mean())
data.head()

Mean rate : 3.247151439817692
Mean comments length : 23.736743993371995


ID                                  UUID  Trip ID  \
0  19469  5f090183-575f-4b68-bfd8-8ca64e271f60      NaN   
1  19487  79fa4190-76bd-4b48-a6aa-c22b1f5f9355      NaN   
2  31714  7ff43434-065d-4a08-83b2-9a6077c9d0a3  49934.0   
3  31956  737320b2-0e91-42fa-9f48-3e651b453e02  50342.0   
4  32873  1d83eae9-2658-4cee-9afe-6f4824d3ec47  51909.0   

                                             Comment  Rate  \
0                        Sans assistance électrique    1.0   
1                              Pas de frein arrière    3.0   
2                                          Ct génial   0.0   
3                                        Marche pas    0.0   
4  Vélo très bien mais « vélo rue » du Borrigo av...   3.0   

                    Created At                   Updated At  \
0     2021-09-26T11:30:17.535Z     2021-09-26T11:30:17.535Z   
1     2021-09-26T14:01:24.832Z     2021-09-26T14:01:24.832Z   
2  2022-02-21T16:43:55.149001Z  2022-02-21T16:43:55.149001Z   
3  2022-02-25T12:28:03.504405Z  2022-02-25T12:28:03.504405Z   
4  2022-03-09T09:26:07.593932Z  2022-03-09T09:26:07.593932Z   

                User Old ID               Trip Old ID         Classe  \
0  60d193e09485da0e5c6c5c51  6150591710168f3d48342d26      Technique   
1  608156dcdeb7eb746a8b7ba0  61507aff10168f3d483c51c9      Technique   
2                       NaN                       NaN  Pas technique   
3                       NaN         ;;;;;;;;;;;;;;;;;            NaN   
4                       NaN                       NaN  Pas technique   

                                               Comms  Length  
0                        Sans assistance électrique       27  
1                              Pas de frein arrière       21  
2                                          Ct génial       9  
3                                        Marche pas       11  
4  Vélo très bien mais « vélo rue » du Borrigo av...      83

In [62]:
data.drop(data[data.Length < 2].index, inplace=True)
#aaaa["Comment"] = aaaa['Comment'].str.normalize('NFKD').str.encode('ASCII', errors='ignore').str.decode('utf-8')
data["Comms"] = data['Comms'].str.normalize('NFKD').str.encode('ASCII', errors='ignore').str.decode('utf-8')
data.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

data["Comms"] = data['Comms'].str.lower()
data.head(2)

ID                                  UUID  Trip ID  \
0  19469  5f090183-575f-4b68-bfd8-8ca64e271f60      NaN   
1  19487  79fa4190-76bd-4b48-a6aa-c22b1f5f9355      NaN   

                       Comment  Rate                Created At  \
0  Sans assistance électrique    1.0  2021-09-26T11:30:17.535Z   
1        Pas de frein arrière    3.0  2021-09-26T14:01:24.832Z   

                 Updated At               User Old ID  \
0  2021-09-26T11:30:17.535Z  60d193e09485da0e5c6c5c51   
1  2021-09-26T14:01:24.832Z  608156dcdeb7eb746a8b7ba0   

                Trip Old ID     Classe                        Comms  Length  \
0  6150591710168f3d48342d26  Technique  sans assistance electrique       27   
1  61507aff10168f3d483c51c9  Technique        pas de frein arriere       21   

                           Tokens  
0  [sans, assistance, electrique]  
1       [pas, de, frein, arriere]

In [61]:
data['Comms'] = data['Comms'].astype(str)
import nltk
data["Tokens"] = data.apply(lambda row: nltk.word_tokenize(row["Comms"]), axis=1)
print(data['Tokens'])

0                          [sans, assistance, electrique]
1                               [pas, de, frein, arriere]
2                                            [ct, genial]
3                                           [marche, pas]
4       [velo, tres, bien, mais, velo, rue, du, borrig...
                              ...                        
4823    [great, service, ., le, velo, tremble, et, les...
4824                                                 [nn]
4825             [lumiere, avant, dirigee, trop, haut, .]
4826    [problemes, rencontres, avec, la, batterie, .,...
4827                                [velo, pas, recharge]
Name: Tokens, Length: 4588, dtype: object


In [64]:
data.to_csv('csv_all_tokenized.csv')

In [63]:
from sklearn.feature_extraction.text import CountVectorizer 

vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7)

X = vectorizer.fit_transform(X.ravel()).toarray()

NameError: name 'X' is not defined

In [68]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfTransformer 
from sklearn.model_selection import train_test_split

# Load data
df = pd.read_csv('csv_all_tokenized.csv')

df = df[df['Classe'].notna()]
df.head(10)
df.shape

(472, 14)

In [69]:
X = df['Tokens']
y = df['Classe']

vectorizer = CountVectorizer(max_features=1500)
X = vectorizer.fit_transform(X.ravel()).toarray()

#tfidfconverter = TfidfTransformer() 
#X = tfidfconverter.fit_transform(X).toarray()

# Split the data into 80% train and 20% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

# Instantiate rf
rf = RandomForestClassifier(n_estimators=25, random_state=1)
            
# Fit rf to the training set    
rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=25, random_state=1)

In [70]:
y_pred = rf.predict(X_test)

In [71]:
print(X_test)
print(y_pred)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['Technique' 'Pas technique' 'Pas technique' 'Technique' 'Pas technique'
 'Technique' 'Technique' 'Pas technique' 'Pas technique' 'Technique'
 'Technique' 'Technique' 'Technique' 'Technique' 'Technique'
 'Pas technique' 'Pas technique' 'Technique' 'Pas technique'
 'Pas technique' 'Pas technique' 'Pas technique' 'Pas technique'
 'Technique' 'Technique' 'Pas technique' 'Technique' 'Technique'
 'Pas technique' 'Pas technique' 'Pas technique' 'Pas technique'
 'Technique' 'Pas technique' 'Pas technique' 'Pas technique'
 'Pas technique' 'Pas technique' 'Pas technique' 'Technique' 'Technique'
 'Pas technique' 'Pas technique' 'Pas technique' 'Pas technique'
 'Pas technique' 'Pas technique' 'Technique' 'Technique' 'Pas technique'
 'Pas technique' 'Pas technique' 'Pas technique' 'Technique' 'Technique'
 'Pas technique' 'Pas technique' 'Pas technique' 'Technique'
 'Pas technique

In [77]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Confusion matrix is : \n", confusion_matrix(y_test, y_pred))
print("Accuracy score is :", accuracy_score(y_test, y_pred))

Confusion matrix is : 
 [[54  2]
 [ 8 31]]
Accuracy score is : 0.8947368421052632
